name: Java CI with Maven

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Compiling and testing Maven
    runs-on: ubuntu-latest
    env:
      MYSQL_URL: ${{secrets.MYSQL_URL}}
      MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE}}
      MYSQL_USERNAME: ${{secrets.MYSQL_USERNAME}}
      MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Initialize MYSQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -h -e "CREATE DATABASE IF NOT EXISTS MYSQL_DATABASE;" -u$MYSQL_USERNAME -p$MYSQL_PASSWORD
      - name: Build with Maven
        run: mvn -B package --file pom.xml