name: Java Compiling Maven

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Compiling Maven
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn compile --file pom.xml