name: Java CI with Maven

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          repository: thejusthomson-csy6225/webapp
          token: ${{ secrets.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 }}
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml