name: Validating packer Packer

on:
    pull_request:
        branches:
            - 'main'


jobs:
  build:
    name: Packer Validate
    runs-on: ubuntu-latest
    env:
        service_account_json: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup-packer

      - name: Init Packer
        run: packer init packer/custom-image.pkr.hcl

      - name: Validate Packer configuration
        run: packer validate -var"credentials_json=${service_account_json}" -var "service_account_email=${service_account_email}" packer/custom-image.pkr.hcl
