name: Validating Packer

on:
    pull_request:
        branches:
            - 'main'


jobs:
  build:
    name: Packer Validate
    runs-on: ubuntu-latest
    env:
      PKR_VAR_project_id: ${{vars.PROJECT_ID}}
      PKR_VAR_source_image_family: ${{vars.SOURCE_IMAGE_FAMILY}}
      PKR_VAR_zone: ${{vars.ZONE}}
      PKR_VAR_ssh_username: ${{vars.SSH_USERNAME}}
      PKR_VAR_image_name: ${{vars.IMAGE_NAME}}
      PKR_VAR_scripts_path: ${{vars.SCRIPTS_PATH}}
      PKR_VAR_jar_source: ${{vars.JAR_SOURCE}}
      PKR_VAR_jar_destination: ${{vars.JAR_DESTINATION}}
      PKR_VAR_network: ${{vars.NETWORK}}
      PKR_VAR_service_account_email: ${{secrets.GCP_SERVICE_ACCOUNT_EMAIL}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        id: setup-packer

      - name: Preparing log directory
        run: |
          sudo chmod -R 733 /var/log  

      - name: Build with Maven
        run: mvn -B package -DskipTests=true --file pom.xml

      - name: Init Packer
        run: packer init packer/custom-image.pkr.hcl

      - name: Format Packer configuration
        run: packer fmt -check ./packer/custom-image.pkr.hcl

      - name: Validate Packer configuration
        run: packer validate ./packer/.